### ISSUE TITLE
 Certificate for <vocabularies.odata.org> doesn't match any of the subject alternative names

### ISSUE THREAD

**Issue by erviszyka** [OData/odataorg.github.io#255]
I get the following error message using the odata client

`nested exception is org.apache.olingo.client.api.http.HttpClientException: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <vocabularies.odata.org> doesn't match any of the subject alternative names: [*.azurewebsites.net, *.scm.azurewebsites.net, *.azure-mobile.net, *.scm.azure-mobile.net, *.sso.azurewebsites.net]] with root cause`

when I access the site directly (https://vocabularies.odata.org) I get a certificate error and a no secure warning.

it seems that the certificate is issued to `*.azurewebsite.net` and not `*.odata.org`

Not sure if this is the correct repo to report. If not please advise where to open the ticket

**Comment by mickle00** [comment]
Also seeing this on example services like https://services.odata.org/v4/(S(hzzvj1nir0fn0ec2gtkbslb5))/TripPinServiceRW/

**Comment by mikepizzo** [comment]
Thanks for the heads up.

We are in the process of updating all of our certs and hope to have this resolved shortly.

**Comment by rikat-ms** [comment]
Hi, one of my customers has encountered this issue in the third party software which uses this site. Since it's affected the customer's business, would you please update the certs as soon as possible?

**Comment by spantaleoni** [comment]
Good morning all! 
We are facing the same issue again since today.
What is going on exactly?

**Comment by n4uti** [comment]
Hi! Same issue encountered. Please assign correct certificates, Thanks!

**Comment by Sreejithpin** [comment]
Hi, Fixed the certificates . Please see

**Comment by Dhanush-Chikoti** [comment]
@Sreejithpin Can you please explain to us the root cause? It will be useful for us to communicate internally with our teams when this issue occurs again in the future. Because, this issue happened twice in the past 1 week, which is a show stopper for our Business. :)

**Comment by mikepizzo** [comment]
Background:

Due to internal serviceability requirements, we had to rotate our SSL certificates to use certificates from a different authority.

Rotating certificates should be possible without down-time.  However, as part of this rotation we decided to opportunistically make a change to the applicability of the certificates to also allow https://odata.org (without the "www." prefix).

We made the change over the week-end to reduce impact, but were unaware that the vocabularies.odata.org endpoint were still in use by production applications (most of the vocabularies hosted there are older versions of vocabularies that are now hosted by OASIS at https://github.com/oasis-tcs/odata-vocabularies/tree/master/vocabularies.)

So the impact to applications was due to a lack of understanding about who was continuing to use these vocabularies and how.

This is an ongoing issue with our support of OData -- we know that people are using it through anecdotal evidence, but have no real telemetry on who is doing what with OData.  We only hear from customers when something breaks, which is fortunately not very often, but is obviously no less of an issue for customers when things do break.

As follow up to this issue we'd like to better understand how clients are using the vocab endpoint (including which vocabularies they are accessing) and whether they are using OData V4.0 or an earlier version.

In the meantime, we have updated our SOP for rolling certs to call out the impact on production apps using vocabularies.odata.org to avoid downtime and business impact in the future.

**Comment by erviszyka** [comment]
Not sure if this can help you or it's answering your question but in my case I am using the Java Apache Olingo library (v.4.7.1) to read/write data to Microsoft Dynamics 365.

I create a new OData Client using `ODataClientclient = ODataClientFactory.getEdmEnabledClient("https://my-company.api.crm4.dynamics.com/api/data/v9.1");`.

The library internally calls `https://my-company.api.crm4.dynamics.com/api/data/v9.1/$metadata` to retrieve the metadata document and the response looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:Reference Uri="http://vocabularies.odata.org/OData.Community.Keys.V1.xml">
        <edmx:Include Namespace="OData.Community.Keys.V1" Alias="Keys" />
        <edmx:IncludeAnnotations TermNamespace="OData.Community.Keys.V1" />
    </edmx:Reference>
    <edmx:Reference Uri="http://vocabularies.odata.org/OData.Community.Display.V1.xml">
        <edmx:Include Namespace="OData.Community.Display.V1" Alias="Display" />
        <edmx:IncludeAnnotations TermNamespace="OData.Community.Display.V1" />
    </edmx:Reference>
    <edmx:DataServices>
        <Schema Namespace="Microsoft.Dynamics.CRM" Alias="mscrm" xmlns="http://docs.oasis-open.org/odata/ns/edm">
	....
	....
	....
    </edmx:DataServices>
</edmx:Edmx>
```

This metadata document I think it's used by the library to validate and/or serialize/deserialize the request (or response) to Microsoft Dynamics 365

**Comment by n4uti** [comment]
Same usage in our company as @erviszyka described.

**Comment by mikepizzo** [comment]
That actually is very useful information -- thanks @erviszyka  and @n4uti!
